### ISSUE TITLE
Support multilingual

### ISSUE THREAD

**Issue by jcs090218** [lem-project/lem-page#13]
Like we have discussed in https://github.com/lem-project/lem/issues/644#issuecomment-1575240615.

This is a TODO rather than an issue. ;)

cc @cxxxr @Sasanidas

**Comment by Sasanidas** [comment]
So, I added the initial support for multi-language https://github.com/lem-project/lem-page/commit/d9e81a13ea657c7364c068f82bd937e69005e4a1.

Now comes the long part which is translating the webpage (the first language was japanese, feel free to also add chinese) I'm not well verse in any of those language (I can translate it to spanish tho).

**Comment by jcs090218** [comment]
> So, I added the initial support for multi-language https://github.com/lem-project/lem-page/commit/d9e81a13ea657c7364c068f82bd937e69005e4a1.

Awesome! Thank you! :D 

I've opened PR in #14. This added Chinese language button on the top right (no translation yet).

**Comment by Sasanidas** [comment]
Given that multilingual support is in place, can we close this issue? @jcs090218
