### ISSUE TITLE
TOC for the current page

### ISSUE THREAD

**Issue by vindarel** [lem-project/lem-page#23]
Do you know a way to get the TOC of the current page?

If you take https://lem-project.github.io/lem-page/usage/usage/ there are many sections now. We should either split this page, or have an inline table of contents.

**Comment by Sasanidas** [comment]
I added TOC for a few pages (https://github.com/lem-project/lem-page/commit/1b969f6c5fb20483aa8401a6c4d0a7b9791fa5ee) that seems lo be longer and with a list of links are easier to navigate :+1:

**Comment by vindarel** [comment]
As simple as `{{< toc >}}`, cool.
